### ISSUE TITLE
GtkFlowBox children re-positioning

### ISSUE THREAD

**Issue by hythm7** [hythm7/Z#2]
GtkFlowBox does not allow changing children positions like GtkGrid does (via top_attach, left_attach). 
Is there a way to re-position FlowBox children? (Flip, Rotate,..)

The reason I can't use GtkGrid is because I need support for selection of children widgets, which GtkGrid does not support.

 
Complete Grid Example:
https://github.com/hythm7/gtk-examples/blob/master/grid-children-reposition.p6

Incomplete FlowBox example:
https://github.com/hythm7/gtk-examples/blob/master/flowbox-children-reposition.p6

**Comment by hythm7** [comment]
@Xliff Any suggestion regarding this?

**Comment by hythm7** [comment]
the sorting it self is not much, the children will not exceed 500. basically what I have in mind is When the user press "f" then all children (or the square selcted ones) will be flipped horizontaly, when press 'SHIFT + F' flip vertically. same for Rotate ("r", "SHIFT + R") and other transformation.

**Comment by Xliff** [comment]
OK. Then your best bet is to track the actual representation outside of the flowbox, so when you do these operations, All you then need is to clear the flowbox and then re-add according to the new order.

GTK::FlowBox still needs some loving to support this, however. I will be working on that, this week.

**Comment by hythm7** [comment]
If I understood correctly, then thats exactly what i have already, I have an array of the widgets and rearrange the array with every operation.
Thank you

**Comment by Xliff** [comment]
OK, then I can have this updated, by tomorrow.

**Comment by hythm7** [comment]
@Xliff I'm using this example to remove all children from FlowBox and repopulate with ew children. for some reason I can't make it work 100%.

This is the example I'm using, the expected behavior is:
after clicking swap button, all children will be removed, then flowbox adds new created ones.
 I also left few comments inside the example.
https://github.com/hythm7/gtk-examples/blob/master/flowbox-children-reposition.p6

One thing I noticed, I think GTK::FlowBox.new.add(GTK::Button.new) was working yesterday, not I have to wrap it add the button to FlowBoxChild first, otherwise I get this error:
`No such method 'get-child' for invocant of type 'Sub+{NativeCall::Native[Sub,List]}'`

**Comment by hythm7** [comment]
Above comment updated.

**Comment by Xliff** [comment]
Yes. This is what happens when I work late.  I plan on getting everything working, today. I've been tasked with several other things, so I haven't yet circled back to testing what I wrote. Thanks for letting me know where I need to focus.

**Comment by Xliff** [comment]
Yep! That's what I was worried about. Can you do a $button.upref before you add it to the GTK::FlowBox, remove it and then check $button to see if it still exists? That would help a lot!

**Comment by hythm7** [comment]
Yes, after calling $button.pref,   button exist and $button.label outputs the correct label.

**Comment by Xliff** [comment]
So it turns out that when you need to reuse elements in a GTK::FlowBox, you are _forced_ to upref the GTK::FlowBoxChild, and not the widgets within!

Here is a modified version of your swap code that, with the latest changes, seems to work.

In this, you are forced to do the FlowBoxChild wrapping yourself, so that you can upref the FBC before adding it to the FlowBox. You would have to do this every time you refresh that container.

```perl6
use GTK::Application;
use GTK::Raw::Types;
use GTK::Compat::Types;
use GTK::Box;
use GTK::Button;
use GTK::FlowBox;
use GTK::FlowBoxChild;

my $app = GTK::Application.new(
  title  => 'org.genex.test.widget',
  width  => 400,
  height => 400
);

$app.activate.tap({
  CATCH { default { .message.say; $app.exit } }

  my GTK::Button $exit .= new_with_label: <exit>;
  my GTK::Button $swap .= new_with_label: <swap>;
  $exit.clicked.tap: { $app.exit  };

  my GTK::Button $a .= new_with_label: <a>;
  my GTK::Button $b .= new_with_label: <b>;
  my GTK::Button $c .= new_with_label: <c>;
  my GTK::Button $d .= new_with_label: <d>;
  my GTK::Button $e .= new_with_label: <e>;
  my GTK::Button $f .= new_with_label: <f>;

  my @fbc;
  my @buttons = ($a, $b, $c, $d, $e, $f);
  @buttons.map({ .relief = GTK_RELIEF_NONE });

  my GTK::FlowBox $flowbox .= new;
  $flowbox.min_children_per_line = 3;
  $flowbox.max_children_per_line = 3;
  $flowbox.halign = GTK_ALIGN_START;
  $flowbox.valign = GTK_ALIGN_START;
  $flowbox.homogeneous = True;
  $flowbox.selection-mode = GTK_SELECTION_MULTIPLE;

  for @buttons -> $btn {
    @fbc.push: (my $fbc = GTK::FlowBoxChild.new);
    $fbc.add($btn);
    $fbc.upref;
    $flowbox.add: $fbc;
  }

  my $box = GTK::Box.new-vbox();
  $box.pack_start($flowbox, False, False, 0);
  $box.pack_start($swap, False, False, 0);
  $box.pack_start($exit, False, False, 0);

  $swap.clicked.tap({
    $flowbox.remove-all;
    @fbc = (@fbc[3..5], @fbc[0..2]).flat;
    for @fbc {
      .upref;
      $flowbox.add: $_;
    }
    $flowbox.show-all();
  });

  $app.window.add: $box;
  $app.show_all;
});

$app.run;
```

**Comment by hythm7** [comment]
That worked for me. thank you.

I will probably revisit this and  re-arrange the children by the sort_func of FlowBox (when it's ready) and compare the performance. but that will be in the second phase of the project.

**Comment by Xliff** [comment]
I can actually, _make_ that ready. Tell you what. I will reimplement that with a sort function and let you know when it is ready.

**Comment by hythm7** [comment]
Xliff++ :)

**Comment by Xliff** [comment]
Changes commited to p6-GtkPlus. Example now looks like this:

```perl6
use GTK::Application;
use GTK::Raw::Types;
use GTK::Compat::Types;
use GTK::Box;
use GTK::Button;
use GTK::FlowBox;
use GTK::FlowBoxChild;

my $app = GTK::Application.new(
  title  => 'org.genex.test.widget',
  width  => 400,
  height => 400
);

my %sort-order;

$app.activate.tap({
  CATCH { default { .message.say; $app.exit } }

  my GTK::Button $exit .= new_with_label: <exit>;
  my GTK::Button $swap .= new_with_label: <swap>;
  $exit.clicked.tap: { $app.exit  };

  my GTK::Button $a .= new_with_label: <a>;
  my GTK::Button $b .= new_with_label: <b>;
  my GTK::Button $c .= new_with_label: <c>;
  my GTK::Button $d .= new_with_label: <d>;
  my GTK::Button $e .= new_with_label: <e>;
  my GTK::Button $f .= new_with_label: <f>;

  my @fbc;
  my @buttons = ($a, $b, $c, $d, $e, $f);
  @buttons.map({ .relief = GTK_RELIEF_NONE });

  my GTK::FlowBox $flowbox .= new;
  $flowbox.min_children_per_line = 3;
  $flowbox.max_children_per_line = 3;
  $flowbox.halign = GTK_ALIGN_START;
  $flowbox.valign = GTK_ALIGN_START;
  $flowbox.homogeneous = True;
  $flowbox.selection-mode = GTK_SELECTION_MULTIPLE;

  for @buttons -> $btn {
    @fbc.push: (my $fbc = GTK::FlowBoxChild.new);
    $fbc.add($btn);
    $flowbox.add: $fbc;
  }

  my $box = GTK::Box.new-vbox();
  $box.pack_start($flowbox, False, False, 0);
  $box.pack_start($swap, False, False, 0);
  $box.pack_start($exit, False, False, 0);

  sub reset-order {
    my $c = 0;
    for @fbc {
      %sort-order{ +.flowboxchild.p } = $c++;
      .changed;
    }
  }

  $swap.clicked.tap({
    @fbc = (@fbc[3..5], @fbc[0..2]).flat;
    reset-order();
  });

  reset-order();
  $flowbox.set-sort-func(-> $c1, $c2, $ --> gint {
    CATCH { default { .message.say } }
    my gint $r = %sort-order{ +$c1.p } <=> %sort-order{ +$c2.p };
    $r;
  });
  $app.window.add: $box;
  $app.show_all;
});

$app.run;
```

**Comment by hythm7** [comment]
Xliff, I checked how you fixed the sort function for GTK::FlowBox, and the arguments for the the function is of GtkFlowBox not GtkFlowBoxChild. Why is that so?
https://github.com/Xliff/p6-GtkPlus/commit/cbed0476c384f4f5c9c0f4d486e8adf4f50f0c73#diff-7cb4cc5c0c044fcf9cfbee559d059a0dR126

How do I refer to the child of the FlowBoxChild in the sort function? For example if I want to sort by the label the label of the button inside the FlowBoxChild, Something like this:
 ```
$!flowbox.set-sort-func(-> $c1, $c2, $ --> gint {
       # my gint $r = $c1.p.flowboxchild.get-child.label cmp $c1.p.flowboxchild.get-child.label 
          my gint $r = +$c1.p <=> +$c2.p;
    $r;
  });
```
